girls/blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.PostCreateView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostEditView.as_view(), name='post_edit'),
]

girls/girls/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog')),
]

girls/blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey('auth.User')
    created_at = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-published_date',)

girls/blog/views.py
from django.utils import timezone
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from .models import Post


class PostListView(ListView):

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now())


class PostDetailView(DetailView):

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now())

class PostCreateView(CreateView):
    model = Post
    fields = 'title', 'content'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.published_date = timezone.now()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.object.id})

class PostEditView(UpdateView):
    model = Post
    fields = 'title', 'content'

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.object.id})

girls/blog/templates/blog/base.html
{% load staticfiles %}
<html>
	<head>
		<title>Django Girls blog</title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="{% static 'css/blog.css' %}">
	</head>

  <body>
		<div class="page-header">
			{% if user.is_authenticated %}
			<a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
			{% endif %}
			<h1><a href="/">Django Girls Blog</a></h1>
		</div>
    <div class="content container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

girls/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
  <div class="post">
    {% if object.published_date %}
      <div class="date">
        {{ object.published_date }}
      </div>
    {% endif %}
		{% if user.is_authenticated %}
		<a class="btn btn-default" href="{% url 'blog:post_edit' pk=object.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
		{% endif %}
    <h1>{{ object.title }}</h1>
    <p>{{ object.content|linebreaksbr }}</p>
  </div>
{% endblock %}

girls/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %}
  <h1>New post</h1>
  <form method="POST" class="post-form">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
  </form>
{% endblock %}

girls/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
{% for i in object_list %}
	<div class="post">
		<div class="date">
			<p>published: {{ i.published_date }}</p>
		</div>
		<h1><a href="{% url 'blog:post_detail' pk=i.pk %}">{{ i.title }}</a></h1>
		<p>{{ i.content|linebreaksbr }}</p>
	</div>
{% endfor %}
{% endblock %}